# -*- coding: utf-8 -*-
"""soal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154Lmm0n94gzLNLQvrbbMhneQRAXpEVGo
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class PestDiagnosis(KnowledgeEngine):
    @Rule(Fact(dm=True) & Fact(bh=True) & Fact(tl=True))
    def daun_busuk_berat(self):
        print("Diagnosis: Tanaman mengalami 'Daun Busuk Berat'.")

    @Rule(Fact(dm=True) & Fact(bh=True) & NOT(Fact(db=True)) & NOT(Fact(tl=True)))
    def jamur_hitam(self):
        print("Diagnosis: Tanaman terkena 'Jamur Hitam'.")

    @Rule(Fact(dm=True) & Fact(db=True) & NOT(Fact(bh=True)) & NOT(Fact(tl=True)))
    def ulat_daun(self):
        print("Diagnosis: Tanaman terkena 'Ulat Daun'.")

    @Rule(Fact(dm=True) & Fact(tl=True) & NOT(Fact(bh=True)) & NOT(Fact(db=True)))
    def busuk_akar(self):
        print("Diagnosis: Tanaman mengalami 'Busuk Akar'.")

    @Rule(Fact(dm=True) & NOT(Fact(bh=True)) & NOT(Fact(db=True)) & NOT(Fact(tl=True)))
    def kutu_daun(self):
        print("Diagnosis: Tanaman terkena 'Kutu Daun'.")

    @Rule(NOT(Fact(dm=True)))
    def tidak_terdeteksi(self):
        print("Diagnosis: Gejala tidak sesuai, hama tidak terdeteksi.")

def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "dm": ask_question("Apakah daun menguning?"),
        "bh": ask_question("Apakah terdapat bercak hitam?"),
        "db": ask_question("Apakah daun berlubang?"),
        "tl": ask_question("Apakah tanaman layu?")
    }

if __name__ == "__main__":
    symptoms = get_input()
    engine = PestDiagnosis()
    engine.reset()

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))

    engine.run()